from app.controllers.api.auth import AuthController
from app.controllers.api.payment import PaymentController
from app.controllers.api.item import ItemController
from app.controllers.api.item_interactions import ItemInteractionsController
from app.controllers.api.task import TaskController
from app.controllers.api.task_performance import TaskPerformanceController
from app.controllers.api.profile import ProfileController
from app.controllers.api.referral import ReferralController
from app.controllers.api.location import LocationController